Update Installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -523,6 +523,7 @@ inst_dnscrypt () {
     end_op_message
     return
   fi
+  download_file $TARG_DIR 755 $URL_GEN/manager
   if [ -f ${TARG_DIR}/installer ]; then
     local RURL="https://raw.githubusercontent.com/thuantran/dnscrypt-asuswrt-installer/master/installer"
     local LINSTALL=v$(cat "${TARG_DIR}/installer" | grep -m1 "^DI_VERSION=" | grep -oE '[0-9]{1,2}([.][0-9]{1,2})([.][0-9]{1,2})')
@@ -540,12 +541,11 @@ inst_dnscrypt () {
        echo -e "$INFO New DI_VERSION=$RMNSTALL Available!"
        echo -e "$INFO Updating DI_VERSION=$LINSTALL to $RMNSTALL ."
        curl -L -s -k -O $RURL && chmod 0755 installer && installer inst_dnscrypt; mv installer ${TARG_DIR}/installer
-       return
     else
        echo -e "$INFO DI_VERSION=$LINSTALL is current, no new DNScrypt Asuswrt Installer Version Available."
     fi
   else
-  curl -L -s -k -O $RURL && chmod 0755 installer; mv installer ${TARG_DIR}/installer
+    curl -L -s -k -O $RURL && chmod 0755 installer; mv installer ${TARG_DIR}/installer
   fi
   if [ -f ${TARG_DIR}/dnscrypt-proxy ]; then
     local LVERSION=$("${TARG_DIR}/dnscrypt-proxy" -version)
@@ -567,38 +567,40 @@ inst_dnscrypt () {
        if [ -f ${TARG_DIR}/installer ]; then
           toml_nvars_replace "DNSCRYPT_VER=$LVERSION" "DNSCRYPT_VER=$RMERSION" ${TARG_DIR}/installer
        fi
-       download_file $TARG_DIR 755 $URL_GEN/manager
-       download_file $TARG_DIR 644 https://github.com/jedisct1/dnscrypt-proxy/releases/download/${RMERSION}/${RMERSION_TAR} \
-         $RESOLVERS_URL_PREFIX/public-resolvers.md \
-         $RESOLVERS_URL_PREFIX/public-resolvers.md.minisig \
-         $RESOLVERS_URL_PREFIX/relays.md \
-         $RESOLVERS_URL_PREFIX/relays.md.minisig
-       chown nobody:nobody $TARG_DIR/public-resolvers.md $TARG_DIR/public-resolvers.md.minisig $TARG_DIR/relays.md $TARG_DIR/relays.md.minisig
+       download_file $TARG_DIR 644 https://github.com/jedisct1/dnscrypt-proxy/releases/download/${RMERSION}/${RMERSION_TAR}
        tar xzv -C $TARG_DIR -f $TARG_DIR/$RMERSION_TAR
+       if [ $? -ne 0 ]; then
+          echo -e "$ERROR Unable to download dnscrypt-proxy package for your router"
+          end_op_message
+          return
+       fi
+       chown `nvram get http_username`:root $TARG_DIR/$DNSCRYPT_ARCH_TAR/*
+       mv $TARG_DIR/$DNSCRYPT_ARCH_TAR/* $TARG_DIR
+       rm -r $TARG_DIR/$DNSCRYPT_ARCH_TAR $TARG_DIR/$RMERSION_TAR
+       chmod 755 $TARG_DIR/dnscrypt-proxy
     else
-    echo -e "$INFO No New DNScrypt-Proxy Version Available."
-    toml_nvars_replace "DNSCRYPT_VER=$LVERSION" "DNSCRYPT_VER=$RMERSION" ${TARG_DIR}/installer
+      echo -e "$INFO No New DNScrypt-Proxy Version Available."
+      toml_nvars_replace "DNSCRYPT_VER=$LVERSION" "DNSCRYPT_VER=$RMERSION" ${TARG_DIR}/installer
     fi
   else
-  download_file $TARG_DIR 755 $URL_GEN/manager
-  download_file $TARG_DIR 644 https://github.com/jedisct1/dnscrypt-proxy/releases/download/${DNSCRYPT_VER}/${DNSCRYPT_TAR} \
-    $RESOLVERS_URL_PREFIX/public-resolvers.md \
+    download_file $TARG_DIR 644 https://github.com/jedisct1/dnscrypt-proxy/releases/download/${DNSCRYPT_VER}/${DNSCRYPT_TAR}
+    tar xzv -C $TARG_DIR -f $TARG_DIR/$DNSCRYPT_TAR
+    if [ $? -ne 0 ]; then
+      echo -e "$ERROR Unable to download dnscrypt-proxy package for your router"
+      end_op_message
+      return
+    fi
+    chown `nvram get http_username`:root $TARG_DIR/$DNSCRYPT_ARCH_TAR/*
+    mv $TARG_DIR/$DNSCRYPT_ARCH_TAR/* $TARG_DIR
+    rm -r $TARG_DIR/$DNSCRYPT_ARCH_TAR $TARG_DIR/$DNSCRYPT_TAR
+    chmod 755 $TARG_DIR/dnscrypt-proxy
+  fi
+  download_file $TARG_DIR 644 $RESOLVERS_URL_PREFIX/public-resolvers.md \
     $RESOLVERS_URL_PREFIX/public-resolvers.md.minisig \
     $RESOLVERS_URL_PREFIX/relays.md \
     $RESOLVERS_URL_PREFIX/relays.md.minisig
   chown nobody:nobody $TARG_DIR/public-resolvers.md $TARG_DIR/public-resolvers.md.minisig $TARG_DIR/relays.md $TARG_DIR/relays.md.minisig
-  tar xzv -C $TARG_DIR -f $TARG_DIR/$DNSCRYPT_TAR
-  fi
-  if [ $? -ne 0 ]; then
-    echo -e "$ERROR Unable to download dnscrypt-proxy package for your router"
-    end_op_message
-    return
-  fi
-  chown `nvram get http_username`:root $TARG_DIR/$DNSCRYPT_ARCH_TAR/*
-  mv $TARG_DIR/$DNSCRYPT_ARCH_TAR/* $TARG_DIR
-  rm -r $TARG_DIR/$DNSCRYPT_ARCH_TAR $TARG_DIR/$DNSCRYPT_TAR
-  chmod 755 $TARG_DIR/dnscrypt-proxy
-
+  
   del_jffs_script /jffs/scripts/wan-start dnscrypt-start
   del_jffs_script /jffs/scripts/openvpn-event
   del_jffs_script /jffs/scripts/firewall-start
